### ISSUE TITLE
Does not work on Flow standalone application

### ISSUE THREAD

**Issue by mrimann** [mrimann/CacheBreaker#3]
Just found out, that on a standalone Flow 4.1.x based application (without Neos), the composer install runs through without issues - but then, Flow does not compile anymore, because of a missing package (which is around in a Neos installation).

Exeption:
**Required class "OpsDev\CacheBreaker\FusionObjects\ResourceUriImplementation" could not be loaded properly for reflection.**

Nested exception:
**Required class "Neos\Fusion\FusionObjects\AbstractFusionObject" could not
be loaded properly for reflection.**

Intermediate Workaround is to additionally require/install "neos/fusion 3.3.*".

**Comment by mrimann** [comment]
Besides the technical solution - I'm not sure how we should attack this one on the conceptual side:

- Split it into a Flow-version and a Neos-Version of the package?
- Have a base package that is Flow only + move the Neos specific part into an Add-On package?

Maybe @dimaip has a good idea on this one...?

**Comment by Erdgigant** [comment]
Found a better Workaround (only tested in Flow 5)

Add to Settings.yaml
```yaml
Neos:
  Flow:
    object:
      includeClasses:
        'OpsDev.CacheBreaker': ['OpsDev\CacheBreaker\ViewHelpers\ResourceViewHelper', 'OpsDev\CacheBreaker\Service\ResourceService']
```

This prevents the Class "OpsDev\CacheBreaker\FusionObjects\ResourceUriImplementation" from gettings reflected in the first place.
